"""ajuste no schema para deploy

Revision ID: 531b3ac53911
Revises: 
Create Date: 2025-06-06 22:36:59.675561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531b3ac53911'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_item_id'), table_name='export_item')
    op.drop_table('export_item')
    op.drop_index(op.f('ix_processing_item_id'), table_name='processing_item')
    op.drop_table('processing_item')
    op.drop_index(op.f('ix_import_item_id'), table_name='import_item')
    op.drop_table('import_item')
    op.drop_index(op.f('ix_commercial_item_id'), table_name='commercial_item')
    op.drop_table('commercial_item')
    op.drop_index(op.f('ix_production_item_id'), table_name='production_item')
    op.drop_table('production_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_item',
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('product', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'product', 'year', name=op.f('uq_production_item_type_product_year'))
    )
    op.create_index(op.f('ix_production_item_id'), 'production_item', ['id'], unique=False)
    op.create_table('commercial_item',
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('product', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'product', 'year', name=op.f('uq_production_item_type_product_year'))
    )
    op.create_index(op.f('ix_commercial_item_id'), 'commercial_item', ['id'], unique=False)
    op.create_table('import_item',
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'country', 'year', name=op.f('uq_import_item_type_country_year'))
    )
    op.create_index(op.f('ix_import_item_id'), 'import_item', ['id'], unique=False)
    op.create_table('processing_item',
    sa.Column('color', sa.VARCHAR(), nullable=False),
    sa.Column('cultivar', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cultivar', 'year', name=op.f('uq_processing_item_cultivar_year'))
    )
    op.create_index(op.f('ix_processing_item_id'), 'processing_item', ['id'], unique=False)
    op.create_table('export_item',
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'country', 'year', name=op.f('uq_import_item_type_country_year'))
    )
    op.create_index(op.f('ix_export_item_id'), 'export_item', ['id'], unique=False)
    # ### end Alembic commands ###
