"""add ano to all tables

Revision ID: 977798fdc052
Revises: 
Create Date: 2025-06-04 21:39:34.120614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "977798fdc052"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commercial_items_id"), table_name="commercial_items")
    op.drop_table("commercial_items")
    op.drop_index(op.f("ix_import_items_id"), table_name="import_items")
    op.drop_table("import_items")
    op.drop_index(op.f("ix_production_items_id"), table_name="production_items")
    op.drop_table("production_items")
    op.drop_index(op.f("ix_export_items_id"), table_name="export_items")
    op.drop_table("export_items")
    op.drop_index(op.f("ix_processing_items_id"), table_name="processing_items")
    op.drop_table("processing_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("tipo", sa.VARCHAR(), nullable=False),
        sa.Column("grupo", sa.VARCHAR(), nullable=False),
        sa.Column("cultivar", sa.VARCHAR(), nullable=False),
        sa.Column("quantidade_quilo", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_items_id"), "processing_items", ["id"], unique=False
    )
    op.create_table(
        "export_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("categoria", sa.VARCHAR(), nullable=False),
        sa.Column("pais", sa.VARCHAR(), nullable=False),
        sa.Column("quantidade_quilo", sa.INTEGER(), nullable=True),
        sa.Column("valor_usd", sa.FLOAT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_export_items_id"), "export_items", ["id"], unique=False)
    op.create_table(
        "production_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("categoria", sa.VARCHAR(), nullable=False),
        sa.Column("produto", sa.VARCHAR(), nullable=False),
        sa.Column("quantidade_litros", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_items_id"), "production_items", ["id"], unique=False
    )
    op.create_table(
        "import_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("categoria", sa.VARCHAR(), nullable=False),
        sa.Column("pais", sa.VARCHAR(), nullable=False),
        sa.Column("quantidade_quilo", sa.INTEGER(), nullable=True),
        sa.Column("valor_usd", sa.FLOAT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_items_id"), "import_items", ["id"], unique=False)
    op.create_table(
        "commercial_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("categoria", sa.VARCHAR(), nullable=False),
        sa.Column("produto", sa.VARCHAR(), nullable=False),
        sa.Column("quantidade_litros", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commercial_items_id"), "commercial_items", ["id"], unique=False
    )
    # ### end Alembic commands ###
